import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clamp=(v:unknown,n=1600)=>String(v??"").trim().slice(0,n);
const webHint=/(azi|acum|actual|curent|ultim|recent|nouta|știr|stir|preț|pret|curs valutar|vreme|meteo|lege|legisla|program|orar|2026|caută|cauta|internet|web)/i;
const internalHint=/(bcb|business manager|platform|fleet|maș|masin|curs|vehicul|kilometr|hr|angajat|personal|contract|certific|conced|proiect|lucrare|șantier|santier|incident|crm|lead|ofert|vânz|vanz|task|termen|reper|milestone|cost|cheltu|buget|marj|profit|material|pontaj|ore lucr|prezen|field operations|zi de lucru|manoper)/i;
const financeHint=/(cost|cheltu|buget|marj|profit|contract|financ|materiale.*cost|combustibil.*cost|manoper.*cost|cost.*oră|cost.*ora)/i;
const crmHint=/(crm|lead|ofert|vânz|vanz|follow.?up|pipeline)/i;
const projectHint=/(proiect|lucrare|șantier|santier|task|termen|reper|milestone|întâr|intarz|progres|material)/i;
const timeHint=/(pontaj|ore lucr|prezen|field operations|zi de lucru|cine lucre|lucrează acum|lucreaza acum|manoper)/i;
async function count(q:any){const {count,error}=await q;if(error)throw error;return Number(count||0);}
function history(v:unknown){if(!Array.isArray(v))return [];return v.slice(-10).map((x:any)=>({role:x?.role==="assistant"?"assistant":"user",content:clamp(x?.content,1400)})).filter((x:any)=>x.content);}
function workedMinutes(row:any,now=new Date()){if(!row?.started_at)return 0;const end=row.ended_at?new Date(row.ended_at):now;return Math.max(0,Math.round((end.getTime()-new Date(row.started_at).getTime())/60000)-Number(row.break_minutes||0));}

async function context(admin:any,profile:any,requested:boolean,signal:string){
  const adminRole=Boolean(profile.is_owner||profile.role==="admin"),owner=Boolean(profile.is_owner),now=new Date(),nowIso=now.toISOString(),today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Bucharest",year:"numeric",month:"2-digit",day:"2-digit"}).format(now),longCut=new Date(now.getTime()-3*3600000).toISOString();
  const permissions={role:owner?"owner":profile.role,finance:adminRole,hr:adminRole,companyFleet:adminRole,companyTime:adminRole,destructiveActions:owner};
  if(!requested)return {generatedAt:nowIso,permissions,internalContextLoaded:false,summary:null,details:null};
  let activeTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active"),longTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active").lt("start_at",longCut);
  if(!adminRole){activeTripsQ=activeTripsQ.eq("driver_id",profile.id);longTripsQ=longTripsQ.eq("driver_id",profile.id);}
  let activeTimeQ=admin.from("employee_time_entries").select("id",{count:"exact",head:true}).not("started_at","is",null).is("ended_at",null);
  let pendingTimeQ=admin.from("employee_time_entries").select("id",{count:"exact",head:true}).eq("approval_status","draft").not("ended_at","is",null);
  if(!adminRole){activeTimeQ=activeTimeQ.eq("created_by",profile.id);pendingTimeQ=pendingTimeQ.eq("created_by",profile.id);}
  const queries=[
    count(admin.from("projects").select("id",{count:"exact",head:true})),count(admin.from("projects").select("id",{count:"exact",head:true}).eq("status","in_progress")),
    count(admin.from("project_tasks").select("id",{count:"exact",head:true}).not("status","in","(done,cancelled)")),count(admin.from("project_tasks").select("id",{count:"exact",head:true}).not("status","in","(done,cancelled)").lt("due_date",today)),
    count(admin.from("project_material_requirements").select("id",{count:"exact",head:true}).in("status",["needed","ordered"])),count(admin.from("fleet_vehicles").select("id",{count:"exact",head:true}).eq("is_active",true)),count(activeTripsQ),count(longTripsQ),
    adminRole?count(admin.from("fleet_incidents").select("id",{count:"exact",head:true}).not("status","in","(resolved,closed)")):Promise.resolve(0),
    adminRole?count(admin.from("employees").select("id",{count:"exact",head:true}).eq("employment_status","active")):Promise.resolve(0),
    count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).eq("status","new")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)").or("lead_score.gte.70,priority.in.(high,urgent)")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(accepted,rejected,archived)").lte("next_follow_up_at",nowIso)),
    count(activeTimeQ),count(pendingTimeQ)
  ];
  const [projectsTotal,projectsActive,openTasks,overdueTasks,materialNeeds,activeVehicles,activeTrips,longTrips,openIncidents,activeEmployees,crmActive,crmNew,crmHot,crmDue,activeTimeEntries,pendingTimeEntries]=await Promise.all(queries);
  const {data:projects}=await admin.from("projects").select("id,title,location,status,progress,current_stage,health_status,risk_level,planned_start,planned_end,updated_at").order("updated_at",{ascending:false}).limit(10);
  let projectTasks:any[]=[],milestones:any[]=[],materials:any[]=[],fleet:any[]=[],incidents:any[]=[],hrAlerts:any[]=[],crm:any[]=[],finance:any[]=[],timeEntries:any[]=[],trackedLabor:any[]=[];
  if(projectHint.test(signal)){
    const [{data:t},{data:m},{data:mat}]=await Promise.all([
      admin.from("project_tasks").select("project_id,title,status,priority,due_date").not("status","in","(done,cancelled)").order("due_date",{ascending:true,nullsFirst:false}).limit(20),
      admin.from("project_milestones").select("project_id,title,status,target_date").not("status","eq","cancelled").order("target_date",{ascending:true,nullsFirst:false}).limit(20),
      admin.from("project_material_requirements").select("project_id,item_name,quantity,unit,status,needed_by").in("status",["needed","ordered","delivered"]).order("needed_by",{ascending:true,nullsFirst:false}).limit(25)
    ]);projectTasks=t||[];milestones=m||[];materials=mat||[];
  }
  let tripsQ=admin.from("fleet_trips").select("id,project_id,start_at,end_at,destination,purpose,status,distance_km").eq("status","active").order("start_at",{ascending:true}).limit(12);if(!adminRole)tripsQ=tripsQ.eq("driver_id",profile.id);fleet=(await tripsQ).data||[];
  if(adminRole){incidents=(await admin.from("fleet_incidents").select("incident_type,severity,status,occurred_at,vehicle_drivable").not("status","in","(resolved,closed)").order("occurred_at",{ascending:false}).limit(8)).data||[];hrAlerts=((await admin.rpc("get_hr_alerts",{p_days:30})).data||[]).slice(0,12);}
  if(crmHint.test(signal)){const rows=(await admin.from("quote_requests").select("project_type,location,estimated_budget,desired_start,project_stage,status,priority,lead_score,next_follow_up_at,created_at").not("status","in","(rejected,archived)").order("lead_score",{ascending:false}).limit(10)).data||[];crm=rows.map((x:any)=>({...x,personalDataExcluded:true}));}
  if(timeHint.test(signal)||projectHint.test(signal)||financeHint.test(signal)){
    let tq=admin.from("employee_time_entries").select(adminRole?"id,employee_id,project_id,work_date,started_at,ended_at,break_minutes,approval_status,work_location,employees(full_name),projects(title)":"id,project_id,work_date,started_at,ended_at,break_minutes,approval_status,work_location,projects(title)").gte("work_date",today).order("started_at",{ascending:false}).limit(adminRole?80:20);
    if(!adminRole)tq=tq.eq("created_by",profile.id);
    const rows=(await tq).data||[];
    timeEntries=rows.map((x:any)=>({employee:adminRole?(x.employees?.full_name||"Angajat"):"self",project:x.projects?.title||"General BCB",work_date:x.work_date,started_at:x.started_at,ended_at:x.ended_at,worked_minutes:workedMinutes(x,now),approval_status:x.approval_status,work_location:x.work_location}));
  }
  const todayWorkedMinutes=timeEntries.reduce((s:number,x:any)=>s+Number(x.worked_minutes||0),0);
  if(adminRole&&financeHint.test(signal)){
    const [{data:f},{data:c}]=await Promise.all([admin.from("project_financials").select("project_id,budget_estimated,contract_value,contingency_amount,currency,include_tracked_labor"),admin.from("project_cost_summary").select("project_id,approved_cost,pending_cost,material_cost,labor_cost,fuel_cost,pending_entries")]);
    const summaries=new Map<string,any>((c||[]).map((x:any)=>[x.project_id,x]));finance=(f||[]).map((x:any)=>({...x,costs:summaries.get(x.project_id)||null}));
  }
  if(adminRole&&(financeHint.test(signal)||timeHint.test(signal))){
    const [{data:approvedRows},{data:rateRows},{data:finRows}]=await Promise.all([
      admin.from("employee_time_entries").select("project_id,employee_id,started_at,ended_at,break_minutes").eq("approval_status","approved").not("project_id","is",null).not("ended_at","is",null).limit(1000),
      admin.from("project_labor_rates").select("project_id,employee_id,hourly_cost,currency"),
      admin.from("project_financials").select("project_id,currency,include_tracked_labor")
    ]);
    const rateMap=new Map<string,any>((rateRows||[]).map((r:any)=>[`${r.project_id}:${r.employee_id}`,r]));
    const finMap=new Map<string,any>((finRows||[]).map((r:any)=>[r.project_id,r]));
    const agg=new Map<string,any>();
    for(const row of approvedRows||[]){const fin:any=finMap.get(row.project_id);if(!fin)continue;const rate:any=rateMap.get(`${row.project_id}:${row.employee_id}`);const mins=workedMinutes(row,now),sameCurrency=rate?.currency===fin.currency,hourly=sameCurrency?Number(rate?.hourly_cost||0):0;const prev=agg.get(row.project_id)||{project_id:row.project_id,approved_minutes:0,tracked_labor_cost:0,currency:fin.currency,include_in_job_costing:Boolean(fin.include_tracked_labor)};prev.approved_minutes+=mins;prev.tracked_labor_cost+=mins/60*hourly;agg.set(row.project_id,prev);}trackedLabor=[...agg.values()];
  }
  return {generatedAt:nowIso,permissions,internalContextLoaded:true,summary:{projects:{total:projectsTotal,active:projectsActive,openTasks,overdueTasks,materialNeeds},fleet:{activeVehicles,activeTrips,longTrips,openIncidents},hr:{activeEmployees:adminRole?activeEmployees:null,alertsNext30Days:adminRole?hrAlerts.length:null},crm:{activeLeads:crmActive,newLeads:crmNew,hotLeads:crmHot,followUpsDue:crmDue},fieldOperations:{activeNow:activeTimeEntries,pendingApproval:pendingTimeEntries,todayWorkedMinutes}},details:{projects:projects||[],projectTasks,milestones,materials,activeTrips:fleet,openIncidents:adminRole?incidents:[],hrAlerts:adminRole?hrAlerts:[],crmLeads:crm,finance:adminRole?finance:[],timeEntries,trackedLabor:adminRole?trackedLabor:[]}};
}

function local(question:string,c:any){const q=question.toLowerCase(),x:string[]=[];if(c.internalContextLoaded&&/fleet|maș|mas|curs|vehicul/.test(q))x.push(`Fleet: ${c.summary.fleet.activeTrips} curse active, ${c.summary.fleet.activeVehicles} vehicule active, ${c.summary.fleet.openIncidents} incidente deschise.`);if(c.internalContextLoaded&&projectHint.test(q))x.push(`Proiecte: ${c.summary.projects.active} active, ${c.summary.projects.openTasks} task-uri deschise, ${c.summary.projects.overdueTasks} întârziate și ${c.summary.projects.materialNeeds} necesare materiale deschise.`);if(c.internalContextLoaded&&crmHint.test(q))x.push(`CRM: ${c.summary.crm.activeLeads} lead-uri active, ${c.summary.crm.hotLeads} prioritare, ${c.summary.crm.followUpsDue} follow-up-uri scadente.`);if(c.internalContextLoaded&&timeHint.test(q))x.push(`Field Operations: ${c.summary.fieldOperations.activeNow} pontaje active, ${c.summary.fieldOperations.pendingApproval} de verificat și ${Math.round(c.summary.fieldOperations.todayWorkedMinutes/6)/10} ore înregistrate astăzi în contextul permis.`);if(!x.length)x.push("AI-ul general nu este disponibil momentan, dar contextul operațional BCB rămâne protejat și funcțional.");return x.join("\n\n");}
function text(data:any){return String(data?.output_text||data?.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join("\n")||"").trim();}
function sources(data:any){const m=new Map<string,string>();for(const item of data?.output||[]){if(item?.type==="web_search_call")for(const s of item?.action?.sources||[])if(s?.url)m.set(s.url,s.title||s.url);for(const c of item?.content||[])for(const a of c?.annotations||[])if(a?.url)m.set(a.url,a.title||a.url);}return [...m].slice(0,6).map(([url,title])=>({url,title}));}
async function model(key:string,name:string,q:string,h:any[],ctx:any,page:string,useWeb:boolean){const system=`Ești BCB AI Copilot, creierul de analiză al BCB Business Manager. Ai două obligații egale: să fii foarte util și să respecți strict permisiunile din context.permissions. Nu deduce și nu reconstrui date pe care rolul nu le poate vedea. Nu dezvălui secrete, chei, note medicale, parole, token-uri, date personale CRM sau note private. Pentru Owner/Admin poți analiza financiar numai din context.details.finance și context.details.trackedLabor; pentru Editor nu discuta valori comerciale, rate interne, marjă, salarii, orele colegilor sau HR confidențial. Field Operations din context.details.timeEntries este deja filtrat după rol. Corelează proiecte, task-uri, repere, materiale, pontaj, Fleet, CRM și HR numai când sunt prezente în context. Distinge clar fapt, inferență și recomandare. Nu pretinde că ai executat o acțiune. Pentru acțiuni destructive, financiare sau de aprobare recomandă confirmare explicită. Răspunde în limba utilizatorului, implicit română, clar, scurt și orientat spre decizie.`;const input=[{role:"system",content:[{type:"input_text",text:system}]},...h.map((m:any)=>({role:m.role,content:[{type:m.role==="assistant"?"output_text":"input_text",text:m.content}]})),{role:"user",content:[{type:"input_text",text:`Întrebare: ${q}\nPagina: ${page||"necunoscut"}\n<context_bcb_role_filtered>${JSON.stringify(ctx)}</context_bcb_role_filtered>`}]}];const payload:any={model:name,input,max_output_tokens:1500};if(useWeb)payload.tools=[{type:"web_search",search_context_size:"medium"}];const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`AI provider ${r.status}: ${await r.text()}`);const d=await r.json();return {answer:text(d),sources:sources(d),usedWeb:Boolean((d.output||[]).some((x:any)=>x.type==="web_search_call"))};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"Method not allowed"},405);try{const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("Authorization")||"";const caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const user=(await caller.auth.getUser()).data.user;if(!user)return out({error:"Sesiune invalidă."},401);const {data:profile}=await admin.from("profiles").select("id,role,is_active,is_owner").eq("id",user.id).single();if(!profile?.is_active||!(["admin","editor"].includes(profile.role)||profile.is_owner))return out({error:"Acces indisponibil."},403);const body=await req.json().catch(()=>({})),q=clamp(body?.question,1800),h=history(body?.history),page=clamp(body?.page,140);if(q.length<2)return out({error:"Întrebarea este prea scurtă."},400);const signal=[q,...h.slice(-4).map((m:any)=>m.content),page].join(" "),ctx=await context(admin,profile,internalHint.test(signal),signal),key=Deno.env.get("OPENAI_API_KEY")||"",name=Deno.env.get("OPENAI_MODEL")||"gpt-5.6";let answer="",src:any[]=[],usedWeb=false,mode="operational";if(key){try{const r=await model(key,name,q,h,ctx,page,webHint.test(q));answer=r.answer;src=r.sources;usedWeb=r.usedWeb;if(answer)mode=usedWeb?"hybrid-web":"hybrid";}catch(e){console.error("BCB AI provider fallback",e);}}if(!answer)answer=local(q,ctx);return out({success:true,answer,mode,usedWeb,sources:src,model:key?name:null,permissions:ctx.permissions,capabilities:{generalAI:Boolean(key),webSearch:Boolean(key),internalContext:true,roleAware:true,crmIntelligence:true,projectsIntelligence:true,jobCostingIntelligence:Boolean(ctx.permissions.finance),fieldOperationsIntelligence:true},internalContextLoaded:ctx.internalContextLoaded});}catch(e){console.error("bcb-ai-copilot failed",e);return out({error:e instanceof Error?e.message:String(e)},500);}});
