import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const clamp=(value:unknown,max=1600)=>String(value??"").trim().slice(0,max);
const webHint=/(azi|acum|actual|curent|ultim|recent|nouta|știr|stir|preț|pret|curs valutar|vreme|meteo|lege|legisla|program|orar|scor|clasament|cine este|2026|caută|cauta|internet|web)/i;
const bcbHint=/(bcb|platform|business manager|fleet|maș|masin|curs|vehicul|kilometr|hr|angajat|personal|contract|certific|conced|proiect|lucrare|șantier|santier|incident|crm|lead|ofert|client|vânz|vanz)/i;
const crmHint=/(crm|lead|ofert|client|vânz|vanz|follow.?up|pipeline)/i;

async function count(query:any){const {count,error}=await query;if(error)throw error;return Number(count||0);}
function safeHistory(value:unknown){if(!Array.isArray(value))return [];return value.slice(-10).map((item:any)=>({role:item?.role==="assistant"?"assistant":"user",content:clamp(item?.content,1400)})).filter((x:any)=>x.content.length>0);}
function localAnswer(question:string,ctx:any){
  const q=question.toLowerCase(),lines:string[]=[];
  if(ctx.internalContextLoaded&&/fleet|maș|mas|curs|vehicul|kilometr/.test(q)){lines.push(`Fleet: ${ctx.summary.fleet.activeTrips} curse active, ${ctx.summary.fleet.activeVehicles} vehicule active și ${ctx.summary.fleet.openIncidents} incidente deschise.`);if(ctx.summary.fleet.longTrips>0)lines.push(`${ctx.summary.fleet.longTrips} curse depășesc 3 ore și necesită verificare.`);}
  if(ctx.internalContextLoaded&&/hr|angajat|personal|contract|certific|conced/.test(q)&&ctx.scope==="company")lines.push(`People Operations: ${ctx.summary.hr.activeEmployees} angajați activi și ${ctx.summary.hr.alertsNext30Days} scadențe HR în următoarele 30 de zile.`);
  if(ctx.internalContextLoaded&&/proiect|lucrare|șantier|santier/.test(q))lines.push(`Proiecte: ${ctx.summary.projects.total} înregistrate, ${ctx.summary.projects.active} în desfășurare.`);
  if(ctx.internalContextLoaded&&crmHint.test(q))lines.push(`CRM: ${ctx.summary.crm.activeLeads} lead-uri active, ${ctx.summary.crm.newLeads} noi, ${ctx.summary.crm.hotLeads} cu intenție ridicată și ${ctx.summary.crm.followUpsDue} follow-up-uri scadente.`);
  if(!lines.length)lines.push("Modul AI general necesită cheia OpenAI configurată în Supabase. Nu voi inventa un răspuns general fără modelul AI.");return lines.join("\n\n");
}

async function collectContext(admin:any,profile:any,requested:boolean,signal:string){
  const privileged=Boolean(profile.is_owner||profile.role==="admin");
  if(!requested)return {scope:privileged?"company":"user",generatedAt:new Date().toISOString(),internalContextLoaded:false,summary:null,details:null};
  const now=new Date(),nowIso=now.toISOString(),longTripCutoff=new Date(now.getTime()-3*3600000).toISOString();
  const projectTotalQ=admin.from("projects").select("id",{count:"exact",head:true});
  const projectActiveQ=admin.from("projects").select("id",{count:"exact",head:true}).eq("status","in_progress");
  const activeVehiclesQ=admin.from("fleet_vehicles").select("id",{count:"exact",head:true}).eq("is_active",true);
  let activeTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active");
  let longTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active").lt("start_at",longTripCutoff);
  if(!privileged){activeTripsQ=activeTripsQ.eq("driver_id",profile.id);longTripsQ=longTripsQ.eq("driver_id",profile.id);}
  const openIncidentsQ=privileged?admin.from("fleet_incidents").select("id",{count:"exact",head:true}).not("status","in","(resolved,closed)"):Promise.resolve({count:0,error:null});
  const activeEmployeesQ=privileged?admin.from("employees").select("id",{count:"exact",head:true}).eq("employment_status","active"):Promise.resolve({count:0,error:null});
  const crmActiveQ=admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)");
  const crmNewQ=admin.from("quote_requests").select("id",{count:"exact",head:true}).eq("status","new");
  const crmHotQ=admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)").or("lead_score.gte.70,priority.in.(high,urgent)");
  const crmDueQ=admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(accepted,rejected,archived)").lte("next_follow_up_at",nowIso);
  const [projectsTotal,projectsActive,activeVehicles,activeTrips,longTrips,openIncidents,activeEmployees,crmActive,crmNew,crmHot,crmDue]=await Promise.all([count(projectTotalQ),count(projectActiveQ),count(activeVehiclesQ),count(activeTripsQ),count(longTripsQ),count(openIncidentsQ),count(activeEmployeesQ),count(crmActiveQ),count(crmNewQ),count(crmHotQ),count(crmDueQ)]);

  let hrAlerts:any[]=[],projectDetails:any[]=[],fleetDetails:any[]=[],incidentDetails:any[]=[],crmDetails:any[]=[];
  if(privileged){const {data}=await admin.rpc("get_hr_alerts",{p_days:30});hrAlerts=(data||[]).slice(0,12);}
  const {data:projects}=await admin.from("projects").select("title,location,status,progress,current_stage,updated_at").order("updated_at",{ascending:false}).limit(8);projectDetails=projects||[];
  let trips=admin.from("fleet_trips").select("id,vehicle_id,driver_id,start_at,origin,destination,purpose,status,start_odometer").eq("status","active").order("start_at",{ascending:true}).limit(10);if(!privileged)trips=trips.eq("driver_id",profile.id);const {data:tripRows}=await trips;fleetDetails=tripRows||[];
  if(privileged){const {data:incidents}=await admin.from("fleet_incidents").select("incident_type,severity,status,occurred_at,location_text,vehicle_drivable,estimated_cost").not("status","in","(resolved,closed)").order("occurred_at",{ascending:false}).limit(8);incidentDetails=incidents||[];}
  if(crmHint.test(signal)){
    const {data:leads}=await admin.from("quote_requests").select("project_type,location,estimated_budget,desired_start,project_stage,status,priority,lead_score,next_follow_up_at,created_at").not("status","in","(rejected,archived)").order("lead_score",{ascending:false}).limit(10);
    crmDetails=(leads||[]).map((lead:any)=>({...lead,personalDataExcluded:true}));
  }
  return {scope:privileged?"company":"user",generatedAt:nowIso,internalContextLoaded:true,summary:{projects:{total:projectsTotal,active:projectsActive},fleet:{activeVehicles,activeTrips,longTrips,openIncidents},hr:{activeEmployees,alertsNext30Days:hrAlerts.length},crm:{activeLeads:crmActive,newLeads:crmNew,hotLeads:crmHot,followUpsDue:crmDue}},details:{projects:projectDetails,activeTrips:fleetDetails,openIncidents:incidentDetails,hrAlerts:privileged?hrAlerts:[],crmLeads:crmDetails}};
}

function extractText(data:any){return String(data?.output_text||data?.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join("\n")||"").trim();}
function extractSources(data:any){const found=new Map<string,string>();for(const item of data?.output||[]){if(item?.type==="web_search_call")for(const source of item?.action?.sources||[])if(source?.url)found.set(source.url,source.title||source.url);for(const content of item?.content||[])for(const ann of content?.annotations||[])if(ann?.url)found.set(ann.url,ann.title||ann.url);}return [...found.entries()].slice(0,6).map(([url,title])=>({url,title}));}
async function askModel(apiKey:string,model:string,question:string,history:any[],context:any,page:string,allowWeb:boolean){const system=`Ești BCB AI Copilot, un asistent AI general profesionist integrat în BCB Business Manager. Poți răspunde la întrebări generale, explica, calcula, compara, redacta și ajuta la decizii. Folosește web search doar când informația este actuală sau verificabilă în timp real. Când contextul intern BCB este încărcat, folosește-l numai dacă este relevant și respectă strict rolul utilizatorului. Datele CRM din context sunt intenționat anonimizate; nu încerca să deduci identitatea clienților. Nu dezvălui date sensibile HR, note medicale, date personale, secrete sau chei. Nu pretinde că ai executat acțiuni dacă doar ai oferit recomandări. Răspunde în limba utilizatorului, implicit română, clar și practic.`;const input=[{role:"system",content:[{type:"input_text",text:system}]},...history.map((m:any)=>({role:m.role,content:[{type:m.role==="assistant"?"output_text":"input_text",text:m.content}]})),{role:"user",content:[{type:"input_text",text:`Întrebarea curentă: ${question}\n\nPagina/modulul curent: ${page||"necunoscut"}\n\n<context_intern_bcb>${JSON.stringify(context)}</context_intern_bcb>`}]}];const payload:any={model,input,max_output_tokens:1400};if(allowWeb)payload.tools=[{type:"web_search",search_context_size:"medium"}];const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`AI provider ${response.status}: ${await response.text()}`);const data=await response.json();return {answer:extractText(data),sources:extractSources(data),usedWeb:Boolean((data.output||[]).some((x:any)=>x.type==="web_search_call"))};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("Authorization")||"";const caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:userData}=await caller.auth.getUser();if(!userData.user)return json({error:"Sesiune invalidă."},401);const {data:profile,error:profileError}=await admin.from("profiles").select("id,role,is_active,is_owner").eq("id",userData.user.id).single();if(profileError||!profile?.is_active)return json({error:"Cont inactiv sau profil indisponibil."},403);const body=await req.json().catch(()=>({})),question=clamp(body?.question,1800),history=safeHistory(body?.history),page=clamp(body?.page,120);if(question.length<2)return json({error:"Întrebarea este prea scurtă."},400);const signal=[question,...history.slice(-4).map((m:any)=>m.content),page].join(" "),internalRequested=bcbHint.test(signal),context=await collectContext(admin,profile,internalRequested,signal),apiKey=Deno.env.get("OPENAI_API_KEY")||"",model=Deno.env.get("OPENAI_MODEL")||"gpt-5.6";let answer="",sources:any[]=[],usedWeb=false,mode="operational";if(apiKey){try{const result=await askModel(apiKey,model,question,history,context,page,webHint.test(question));answer=result.answer;sources=result.sources;usedWeb=result.usedWeb;if(answer)mode=usedWeb?"hybrid-web":"hybrid";}catch(error){console.error("BCB AI provider fallback",error);}}if(!answer)answer=localAnswer(question,context);return json({success:true,answer,mode,usedWeb,sources,model:apiKey?model:null,capabilities:{generalAI:Boolean(apiKey),webSearch:Boolean(apiKey),internalContext:true,conversation:true,crmIntelligence:true},internalContextLoaded:internalRequested});}catch(error){console.error("bcb-ai-copilot failed",error);return json({error:error instanceof Error?error.message:String(error)},500);}});
