import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clamp=(v:unknown,n=1600)=>String(v??"").trim().slice(0,n);
const webHint=/(azi|acum|actual|curent|ultim|recent|nouta|știr|stir|preț|pret|curs valutar|vreme|meteo|lege|legisla|program|orar|2026|caută|cauta|internet|web)/i;
const internalHint=/(bcb|business manager|platform|fleet|maș|masin|curs|vehicul|kilometr|hr|angajat|personal|contract|certific|conced|proiect|lucrare|șantier|santier|incident|crm|lead|ofert|vânz|vanz|task|termen|reper|milestone|cost|cheltu|buget|marj|profit|material)/i;
const financeHint=/(cost|cheltu|buget|marj|profit|contract|financ|materiale.*cost|combustibil.*cost)/i;
const crmHint=/(crm|lead|ofert|vânz|vanz|follow.?up|pipeline)/i;
const projectHint=/(proiect|lucrare|șantier|santier|task|termen|reper|milestone|întâr|intarz|progres|material)/i;
async function count(q:any){const {count,error}=await q;if(error)throw error;return Number(count||0);}
function history(v:unknown){if(!Array.isArray(v))return [];return v.slice(-10).map((x:any)=>({role:x?.role==="assistant"?"assistant":"user",content:clamp(x?.content,1400)})).filter((x:any)=>x.content);}

async function context(admin:any,profile:any,requested:boolean,signal:string){
  const adminRole=Boolean(profile.is_owner||profile.role==="admin"),owner=Boolean(profile.is_owner),now=new Date(),nowIso=now.toISOString(),today=nowIso.slice(0,10),longCut=new Date(now.getTime()-3*3600000).toISOString();
  const permissions={role:owner?"owner":profile.role,finance:adminRole,hr:adminRole,companyFleet:adminRole,destructiveActions:owner};
  if(!requested)return {generatedAt:nowIso,permissions,internalContextLoaded:false,summary:null,details:null};
  let activeTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active"),longTripsQ=admin.from("fleet_trips").select("id",{count:"exact",head:true}).eq("status","active").lt("start_at",longCut);
  if(!adminRole){activeTripsQ=activeTripsQ.eq("driver_id",profile.id);longTripsQ=longTripsQ.eq("driver_id",profile.id);}
  const queries=[
    count(admin.from("projects").select("id",{count:"exact",head:true})),count(admin.from("projects").select("id",{count:"exact",head:true}).eq("status","in_progress")),
    count(admin.from("project_tasks").select("id",{count:"exact",head:true}).not("status","in","(done,cancelled)")),count(admin.from("project_tasks").select("id",{count:"exact",head:true}).not("status","in","(done,cancelled)").lt("due_date",today)),
    count(admin.from("project_material_requirements").select("id",{count:"exact",head:true}).in("status",["needed","ordered"])),count(admin.from("fleet_vehicles").select("id",{count:"exact",head:true}).eq("is_active",true)),count(activeTripsQ),count(longTripsQ),
    adminRole?count(admin.from("fleet_incidents").select("id",{count:"exact",head:true}).not("status","in","(resolved,closed)")):Promise.resolve(0),
    adminRole?count(admin.from("employees").select("id",{count:"exact",head:true}).eq("employment_status","active")):Promise.resolve(0),
    count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).eq("status","new")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(rejected,archived)").or("lead_score.gte.70,priority.in.(high,urgent)")),count(admin.from("quote_requests").select("id",{count:"exact",head:true}).not("status","in","(accepted,rejected,archived)").lte("next_follow_up_at",nowIso))
  ];
  const [projectsTotal,projectsActive,openTasks,overdueTasks,materialNeeds,activeVehicles,activeTrips,longTrips,openIncidents,activeEmployees,crmActive,crmNew,crmHot,crmDue]=await Promise.all(queries);
  const {data:projects}=await admin.from("projects").select("id,title,location,status,progress,current_stage,health_status,risk_level,planned_start,planned_end,updated_at").order("updated_at",{ascending:false}).limit(10);
  let projectTasks:any[]=[],milestones:any[]=[],materials:any[]=[],fleet:any[]=[],incidents:any[]=[],hrAlerts:any[]=[],crm:any[]=[],finance:any[]=[];
  if(projectHint.test(signal)){
    const [{data:t},{data:m},{data:mat}]=await Promise.all([
      admin.from("project_tasks").select("project_id,title,status,priority,due_date").not("status","in","(done,cancelled)").order("due_date",{ascending:true,nullsFirst:false}).limit(20),
      admin.from("project_milestones").select("project_id,title,status,target_date").not("status","eq","cancelled").order("target_date",{ascending:true,nullsFirst:false}).limit(20),
      admin.from("project_material_requirements").select("project_id,item_name,quantity,unit,status,needed_by").in("status",["needed","ordered","delivered"]).order("needed_by",{ascending:true,nullsFirst:false}).limit(25)
    ]);projectTasks=t||[];milestones=m||[];materials=mat||[];
  }
  let tripsQ=admin.from("fleet_trips").select("id,project_id,start_at,end_at,destination,purpose,status,distance_km").eq("status","active").order("start_at",{ascending:true}).limit(12);if(!adminRole)tripsQ=tripsQ.eq("driver_id",profile.id);fleet=(await tripsQ).data||[];
  if(adminRole){incidents=(await admin.from("fleet_incidents").select("incident_type,severity,status,occurred_at,vehicle_drivable").not("status","in","(resolved,closed)").order("occurred_at",{ascending:false}).limit(8)).data||[];hrAlerts=((await admin.rpc("get_hr_alerts",{p_days:30})).data||[]).slice(0,12);}
  if(crmHint.test(signal)){const rows=(await admin.from("quote_requests").select("project_type,location,estimated_budget,desired_start,project_stage,status,priority,lead_score,next_follow_up_at,created_at").not("status","in","(rejected,archived)").order("lead_score",{ascending:false}).limit(10)).data||[];crm=rows.map((x:any)=>({...x,personalDataExcluded:true}));}
  if(adminRole&&financeHint.test(signal)){
    const [{data:f},{data:c}]=await Promise.all([admin.from("project_financials").select("project_id,budget_estimated,contract_value,contingency_amount,currency"),admin.from("project_cost_summary").select("project_id,approved_cost,pending_cost,material_cost,labor_cost,fuel_cost,pending_entries")]);
    const summaries=new Map((c||[]).map((x:any)=>[x.project_id,x]));finance=(f||[]).map((x:any)=>({...x,costs:summaries.get(x.project_id)||null}));
  }
  return {generatedAt:nowIso,permissions,internalContextLoaded:true,summary:{projects:{total:projectsTotal,active:projectsActive,openTasks,overdueTasks,materialNeeds},fleet:{activeVehicles,activeTrips,longTrips,openIncidents},hr:{activeEmployees:adminRole?activeEmployees:null,alertsNext30Days:adminRole?hrAlerts.length:null},crm:{activeLeads:crmActive,newLeads:crmNew,hotLeads:crmHot,followUpsDue:crmDue}},details:{projects:projects||[],projectTasks,milestones,materials,activeTrips:fleet,openIncidents:adminRole?incidents:[],hrAlerts:adminRole?hrAlerts:[],crmLeads:crm,finance:adminRole?finance:[]}};
}

function local(question:string,c:any){const q=question.toLowerCase(),x:string[]=[];if(c.internalContextLoaded&&/fleet|maș|mas|curs|vehicul/.test(q))x.push(`Fleet: ${c.summary.fleet.activeTrips} curse active, ${c.summary.fleet.activeVehicles} vehicule active, ${c.summary.fleet.openIncidents} incidente deschise.`);if(c.internalContextLoaded&&projectHint.test(q))x.push(`Proiecte: ${c.summary.projects.active} active, ${c.summary.projects.openTasks} task-uri deschise, ${c.summary.projects.overdueTasks} întârziate și ${c.summary.projects.materialNeeds} necesare materiale deschise.`);if(c.internalContextLoaded&&crmHint.test(q))x.push(`CRM: ${c.summary.crm.activeLeads} lead-uri active, ${c.summary.crm.hotLeads} prioritare, ${c.summary.crm.followUpsDue} follow-up-uri scadente.`);if(!x.length)x.push("AI-ul general nu este disponibil momentan, dar contextul operațional BCB rămâne protejat și funcțional.");return x.join("\n\n");}
function text(data:any){return String(data?.output_text||data?.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join("\n")||"").trim();}
function sources(data:any){const m=new Map<string,string>();for(const item of data?.output||[]){if(item?.type==="web_search_call")for(const s of item?.action?.sources||[])if(s?.url)m.set(s.url,s.title||s.url);for(const c of item?.content||[])for(const a of c?.annotations||[])if(a?.url)m.set(a.url,a.title||a.url);}return [...m].slice(0,6).map(([url,title])=>({url,title}));}
async function model(key:string,name:string,q:string,h:any[],ctx:any,page:string,useWeb:boolean){const system=`Ești BCB AI Copilot, creierul de analiză al BCB Business Manager. Ai două obligații egale: să fii foarte util și să respecți strict permisiunile din context.permissions. Nu deduce și nu reconstrui date pe care rolul nu le poate vedea. Nu dezvălui secrete, chei, note medicale, parole, token-uri, date personale CRM sau note private. Pentru Owner/Admin poți analiza financiar numai din context.details.finance; pentru Editor nu discuta valori comerciale, marjă, salarii sau HR confidențial. Corelează proiecte, task-uri, repere, materiale, Fleet, CRM și HR numai când sunt prezente în context. Distinge clar fapt, inferență și recomandare. Nu pretinde că ai executat o acțiune. Pentru acțiuni destructive sau financiare recomandă confirmare explicită. Răspunde în limba utilizatorului, implicit română, clar, scurt și orientat spre decizie.`;const input=[{role:"system",content:[{type:"input_text",text:system}]},...h.map((m:any)=>({role:m.role,content:[{type:m.role==="assistant"?"output_text":"input_text",text:m.content}]})),{role:"user",content:[{type:"input_text",text:`Întrebare: ${q}\nPagina: ${page||"necunoscut"}\n<context_bcb_role_filtered>${JSON.stringify(ctx)}</context_bcb_role_filtered>`}]}];const payload:any={model:name,input,max_output_tokens:1500};if(useWeb)payload.tools=[{type:"web_search",search_context_size:"medium"}];const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error(`AI provider ${r.status}: ${await r.text()}`);const d=await r.json();return {answer:text(d),sources:sources(d),usedWeb:Boolean((d.output||[]).some((x:any)=>x.type==="web_search_call"))};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"Method not allowed"},405);try{const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("Authorization")||"";const caller=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const user=(await caller.auth.getUser()).data.user;if(!user)return out({error:"Sesiune invalidă."},401);const {data:profile}=await admin.from("profiles").select("id,role,is_active,is_owner").eq("id",user.id).single();if(!profile?.is_active||!(["admin","editor"].includes(profile.role)||profile.is_owner))return out({error:"Acces indisponibil."},403);const body=await req.json().catch(()=>({})),q=clamp(body?.question,1800),h=history(body?.history),page=clamp(body?.page,140);if(q.length<2)return out({error:"Întrebarea este prea scurtă."},400);const signal=[q,...h.slice(-4).map((m:any)=>m.content),page].join(" "),ctx=await context(admin,profile,internalHint.test(signal),signal),key=Deno.env.get("OPENAI_API_KEY")||"",name=Deno.env.get("OPENAI_MODEL")||"gpt-5.6";let answer="",src:any[]=[],usedWeb=false,mode="operational";if(key){try{const r=await model(key,name,q,h,ctx,page,webHint.test(q));answer=r.answer;src=r.sources;usedWeb=r.usedWeb;if(answer)mode=usedWeb?"hybrid-web":"hybrid";}catch(e){console.error("BCB AI provider fallback",e);}}if(!answer)answer=local(q,ctx);return out({success:true,answer,mode,usedWeb,sources:src,model:key?name:null,permissions:ctx.permissions,capabilities:{generalAI:Boolean(key),webSearch:Boolean(key),internalContext:true,roleAware:true,crmIntelligence:true,projectsIntelligence:true,jobCostingIntelligence:Boolean(ctx.permissions.finance)},internalContextLoaded:ctx.internalContextLoaded});}catch(e){console.error("bcb-ai-copilot failed",e);return out({error:e instanceof Error?e.message:String(e)},500);}});