import { requireStaff, supabase, esc } from "./admin-common.js";

let ctx=null,projects=[],ownEntries=[],teamEntries=[],activeEntry=null,timer=null;
const $=s=>document.querySelector(s);
const privileged=()=>Boolean(ctx?.profile?.is_owner||ctx?.profile?.role==="admin");
const nowIso=()=>new Date().toISOString();
const todayRo=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Bucharest",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const fmtTime=v=>v?new Intl.DateTimeFormat("ro-RO",{timeZone:"Europe/Bucharest",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
const fmtDate=v=>v?new Intl.DateTimeFormat("ro-RO",{timeZone:"Europe/Bucharest",day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${String(v).slice(0,10)}T12:00:00+03:00`)):"—";
function workedMinutes(row,live=false){if(!row?.started_at)return 0;const end=row.ended_at?new Date(row.ended_at):(live?new Date():new Date(row.started_at));return Math.max(0,Math.round((end-new Date(row.started_at))/60000)-Number(row.break_minutes||0));}
function duration(mins){const h=Math.floor(mins/60),m=mins%60;return `${h}h ${String(m).padStart(2,"0")}m`;}
function durationClock(row){const total=Math.max(0,Math.floor((Date.now()-new Date(row.started_at).getTime())/1000));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function projectName(id){return projects.find(p=>p.id===id)?.title||"General BCB";}
function message(text,error=false){const el=$("#time-message");if(!el)return;el.hidden=false;el.className=`bcb-time-message${error?" is-error":""}`;el.textContent=text;setTimeout(()=>{el.hidden=true;},5000);}

function localClock(){const tick=()=>{const el=$("#time-live-clock strong");if(el)el.textContent=new Intl.DateTimeFormat("ro-RO",{timeZone:"Europe/Bucharest",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date());};tick();setInterval(tick,1000);}
async function gps(){if(!navigator.geolocation)return null;return await new Promise(resolve=>{const timeout=setTimeout(()=>resolve(null),4500);navigator.geolocation.getCurrentPosition(pos=>{clearTimeout(timeout);resolve({lat:Number(pos.coords.latitude.toFixed(6)),lng:Number(pos.coords.longitude.toFixed(6)),accuracy:Math.round(pos.coords.accuracy||0)});},()=>{clearTimeout(timeout);resolve(null);},{enableHighAccuracy:true,timeout:4000,maximumAge:60000});});}
async function showWorkNotification(){try{if(!("Notification" in window)||!("serviceWorker" in navigator))return;let permission=Notification.permission;if(permission==="default")permission=await Notification.requestPermission();if(permission!=="granted")return;const reg=await navigator.serviceWorker.ready;await reg.showNotification("BCB · Zi de lucru activă",{body:`${projectName(activeEntry?.project_id)} · pontajul este pornit`,icon:"/assets/images/logo.png",badge:"/assets/images/logo.png",tag:"bcb-active-workday",requireInteraction:true,silent:true,data:{url:"/admin/time.html",type:"workday_active"},actions:[{action:"open-time",title:"Deschide pontaj"}]});}catch(error){console.warn("Workday notification",error);}}
async function closeWorkNotification(){try{if(!("serviceWorker" in navigator))return;const reg=await navigator.serviceWorker.ready;const notes=await reg.getNotifications({tag:"bcb-active-workday"});notes.forEach(n=>n.close());}catch{}}

async function loadProjects(){const {data,error}=await supabase.from("projects").select("id,title,status,location").in("status",["draft","in_progress"]).order("title");if(error){console.error("time projects",error);projects=[];}else projects=data||[];const select=$("#time-project");if(select){select.innerHTML='<option value="">General BCB · fără proiect</option>'+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}${p.location?` · ${esc(p.location)}`:""}</option>`).join("");}$("#time-kpi-projects").textContent=String(projects.filter(p=>p.status==="in_progress").length);}

async function loadOwn(){const {data,error}=await supabase.from("employee_time_entries").select("id,project_id,work_date,started_at,ended_at,break_minutes,entry_type,work_location,notes,approval_status,created_at").eq("created_by",ctx.user.id).order("started_at",{ascending:false}).limit(40);if(error){console.error("time own",error);ownEntries=[];}else ownEntries=data||[];activeEntry=ownEntries.find(x=>x.started_at&&!x.ended_at)||null;renderClock();renderOwn();}

async function loadTeam(){if(!privileged())return;const since=new Date(Date.now()-31*86400000).toISOString().slice(0,10);const {data,error}=await supabase.from("employee_time_entries").select("id,employee_id,project_id,work_date,started_at,ended_at,break_minutes,entry_type,work_location,notes,approval_status,created_by,approved_at,employees(full_name,job_title),projects(title)").gte("work_date",since).order("started_at",{ascending:false}).limit(250);if(error){console.error("time team",error);teamEntries=[];}else teamEntries=data||[];renderAdmin();}

function renderClock(){const idle=$("#time-idle-box"),active=$("#time-active-box"),pill=$("#time-state-pill");if(!idle||!active||!pill)return;idle.hidden=Boolean(activeEntry);active.hidden=!activeEntry;pill.className=`bcb-time-state-pill ${activeEntry?"is-live":"is-idle"}`;pill.textContent=activeEntry?"Activ":"Neînceput";clearInterval(timer);if(activeEntry){$("#time-active-project").textContent=projectName(activeEntry.project_id);$("#time-active-since").textContent=`Pornit la ${fmtTime(activeEntry.started_at)} · ${activeEntry.work_location||"Loc nespecificat"}`;$("#time-break-minutes").value=String(activeEntry.break_minutes||0);const tick=()=>{$("#time-active-duration").textContent=durationClock(activeEntry);};tick();timer=setInterval(tick,1000);}renderKpis();}
function renderKpis(){const today=todayRo();const base=privileged()?teamEntries:ownEntries;const todayRows=base.filter(x=>x.work_date===today);const mins=todayRows.reduce((s,x)=>s+workedMinutes(x,!x.ended_at),0);$("#time-kpi-hours").textContent=duration(mins);$("#time-kpi-live").textContent=String(todayRows.filter(x=>x.started_at&&!x.ended_at).length);$("#time-kpi-pending").textContent=String(privileged()?teamEntries.filter(x=>x.approval_status==="draft"&&x.ended_at).length:ownEntries.filter(x=>x.approval_status==="draft"&&x.ended_at).length);}
function statusPill(status){const label=status==="approved"?"Aprobat":status==="rejected"?"Respins":"În verificare";return `<span class="bcb-time-status is-${esc(status||"draft")}">${label}</span>`;}
function ownRow(row){const live=!row.ended_at;return `<article class="bcb-time-row${live?" is-active":""}"><div class="bcb-time-row-main"><strong>${esc(fmtDate(row.work_date))}</strong><small>${esc(row.work_location||"BCB Group")}</small></div><div class="bcb-time-row-project"><strong>${esc(projectName(row.project_id))}</strong><small>${live?"În lucru acum":statusPill(row.approval_status)}</small></div><div class="bcb-time-row-time"><strong>${live?duration(workedMinutes(row,true)):duration(workedMinutes(row))}</strong><small>${esc(fmtTime(row.started_at))} – ${live?"acum":esc(fmtTime(row.ended_at))}${row.break_minutes?` · pauză ${Number(row.break_minutes)}m`:""}</small></div><div></div></article>`;}
function renderOwn(){const box=$("#time-history");if(!box)return;box.innerHTML=ownEntries.length?ownEntries.slice(0,20).map(ownRow).join(""):'<div class="bcb-time-empty">Nu există încă pontaje. Primul START va apărea aici.</div>';renderKpis();}

function renderAdmin(){const zone=$("#time-admin-zone");if(!zone)return;zone.hidden=!privileged();if(zone.hidden)return;const active=teamEntries.filter(x=>x.started_at&&!x.ended_at);$("#time-team-live").innerHTML=active.length?active.map(x=>`<span class="bcb-time-live-chip"><i class="fa-solid fa-circle"></i><strong>${esc(x.employees?.full_name||"Angajat")}</strong> · ${esc(x.projects?.title||"General BCB")} · ${duration(workedMinutes(x,true))}</span>`).join(""):'<div class="bcb-time-empty">Nimeni nu are pontaj activ acum.</div>';renderAdminList();renderKpis();}
function renderAdminList(){const box=$("#time-admin-list");if(!box)return;const filter=$("#time-admin-filter")?.value||"all";let rows=teamEntries.filter(x=>filter==="all"||filter==="active"?true:true);if(filter==="active")rows=teamEntries.filter(x=>!x.ended_at);else if(filter!=="all")rows=teamEntries.filter(x=>x.approval_status===filter);rows=rows.slice(0,80);box.innerHTML=rows.length?rows.map(x=>{const live=!x.ended_at;const actions=!live&&x.approval_status==="draft"?`<div class="bcb-time-actions"><button data-time-id="${esc(x.id)}" data-action="approve" title="Aprobă"><i class="fa-solid fa-check"></i></button><button data-time-id="${esc(x.id)}" data-action="reject" title="Respinge"><i class="fa-solid fa-xmark"></i></button></div>`:`<div class="bcb-time-actions">${statusPill(x.approval_status)}</div>`;return `<article class="bcb-time-row${live?" is-active":""}"><div class="bcb-time-row-main"><strong>${esc(x.employees?.full_name||"Angajat")}</strong><small>${esc(x.employees?.job_title||fmtDate(x.work_date))}</small></div><div class="bcb-time-row-project"><strong>${esc(x.projects?.title||"General BCB")}</strong><small>${esc(x.work_location||fmtDate(x.work_date))}</small></div><div class="bcb-time-row-time"><strong>${duration(workedMinutes(x,live))}</strong><small>${esc(fmtTime(x.started_at))} – ${live?"acum":esc(fmtTime(x.ended_at))}</small></div>${actions}</article>`;}).join(""):'<div class="bcb-time-empty">Nu există pontaje pentru filtrul selectat.</div>';}

async function startWork(){if(activeEntry)return;const btn=$("#time-start");btn.disabled=true;btn.querySelector("strong").textContent="SE PORNEȘTE…";const pos=await gps();const payload={project_id:$("#time-project").value||null,work_date:todayRo(),started_at:nowIso(),break_minutes:0,entry_type:"work",work_location:$("#time-location").value,notes:$("#time-start-note").value.trim()||null,created_by:ctx.user.id,updated_by:ctx.user.id,approval_status:"draft",source:"self_clock",clock_in_lat:pos?.lat??null,clock_in_lng:pos?.lng??null,clock_in_accuracy:pos?.accuracy??null};const {data,error}=await supabase.from("employee_time_entries").insert(payload).select("id,project_id,work_date,started_at,ended_at,break_minutes,entry_type,work_location,notes,approval_status,created_at").single();btn.disabled=false;btn.querySelector("strong").textContent="START LUCRU";if(error){console.error("start work",error);message(error.message?.includes("one_open")?"Ai deja un pontaj activ.":"Pontajul nu a putut fi pornit. Verifică asocierea contului cu angajatul.",true);await loadOwn();return;}activeEntry=data;$("#time-start-note").value="";message("Ziua de lucru a fost pornită și sincronizată.");await showWorkNotification();await loadOwn();if(privileged())await loadTeam();}
async function stopWork(){if(!activeEntry)return;const btn=$("#time-stop");btn.disabled=true;btn.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> SE ÎNCHEIE…';const pos=await gps();const breakMinutes=Math.max(0,Math.min(600,Number($("#time-break-minutes").value||0)));const endNotes=$("#time-stop-note").value.trim();const merged=[activeEntry.notes,endNotes].filter(Boolean).join(" · ").slice(0,500)||null;const {error}=await supabase.from("employee_time_entries").update({ended_at:nowIso(),break_minutes:breakMinutes,notes:merged,clock_out_lat:pos?.lat??null,clock_out_lng:pos?.lng??null,clock_out_accuracy:pos?.accuracy??null,updated_by:ctx.user.id}).eq("id",activeEntry.id);btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-square"></i> ÎNCHEIE ZIUA';if(error){console.error("stop work",error);message("Pontajul nu a putut fi închis. Nu s-a pierdut — rămâne activ și poți încerca din nou.",true);return;}message("Ziua de lucru a fost încheiată. Pontajul a intrat la verificare.");$("#time-stop-note").value="";await closeWorkNotification();await loadOwn();if(privileged())await loadTeam();}
async function approvalAction(event){const button=event.target.closest("button[data-time-id]");if(!button||!privileged())return;const status=button.dataset.action==="approve"?"approved":"rejected";button.disabled=true;const {error}=await supabase.from("employee_time_entries").update({approval_status:status,updated_by:ctx.user.id}).eq("id",button.dataset.timeId);if(error){message("Validarea pontajului a eșuat.",true);button.disabled=false;return;}message(status==="approved"?"Pontaj aprobat.":"Pontaj respins pentru verificare.");await loadTeam();}
function askAI(){const q=privileged()?"Analizează pontajul și Field Operations BCB de azi. Spune-mi cine este activ, câte ore sunt înregistrate, ce pontaje așteaptă aprobare, ce proiecte concentrează munca și ce necesită atenție. Nu expune salarii sau date personale inutile.":"Analizează pontajul meu de azi și spune-mi pe scurt timpul lucrat, proiectul asociat și dacă există ceva de verificat în ziua mea de lucru.";window.dispatchEvent(new CustomEvent("bcb:copilot-open",{detail:{question:q}}));}

function bind(){$("#time-start")?.addEventListener("click",startWork);$("#time-stop")?.addEventListener("click",stopWork);$("#time-admin-list")?.addEventListener("click",approvalAction);$("#time-admin-filter")?.addEventListener("change",renderAdminList);$("#time-ai")?.addEventListener("click",askAI);}
async function init(){ctx=await requireStaff();if(!ctx?.user)return;$("#time-role-badge").innerHTML=`<i class="fa-solid fa-shield-halved"></i> ${ctx.profile?.is_owner?"Owner":ctx.profile?.role==="admin"?"Administrator":"Editor"}`;$("#time-admin-zone").hidden=!privileged();localClock();bind();await loadProjects();await Promise.all([loadOwn(),privileged()?loadTeam():Promise.resolve()]);setInterval(()=>{if(privileged())loadTeam();},90000);}
init();
