create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text not null unique,
  page_key text not null,
  content_type text not null check (content_type in ('text','image')),
  value text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists site_content_page_idx
on public.site_content(page_key, content_key);

alter table public.site_content enable row level security;

drop policy if exists "public can read site content" on public.site_content;
create policy "public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert site content" on public.site_content;
create policy "admins can insert site content"
on public.site_content for insert
to authenticated
with check (public.is_bcb_admin() and updated_by = auth.uid());

drop policy if exists "admins can update site content" on public.site_content;
create policy "admins can update site content"
on public.site_content for update
to authenticated
using (public.is_bcb_admin())
with check (public.is_bcb_admin());

drop policy if exists "admins can delete site content" on public.site_content;
create policy "admins can delete site content"
on public.site_content for delete
to authenticated
using (public.is_bcb_admin());

create or replace function public.site_content_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_content_set_updated_at on public.site_content;
create trigger site_content_set_updated_at
before update on public.site_content
for each row execute function public.site_content_touch_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-content',
  'site-content',
  true,
  20971520,
  array['image/jpeg','image/png','image/webp','image/avif']
)
on conflict (id) do update
set public = true,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view site content images" on storage.objects;
create policy "public can view site content images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'site-content');

drop policy if exists "admins can upload site content images" on storage.objects;
create policy "admins can upload site content images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'site-content' and public.is_bcb_admin());

drop policy if exists "admins can update site content images" on storage.objects;
create policy "admins can update site content images"
on storage.objects for update
to authenticated
using (bucket_id = 'site-content' and public.is_bcb_admin())
with check (bucket_id = 'site-content' and public.is_bcb_admin());

drop policy if exists "admins can delete site content images" on storage.objects;
create policy "admins can delete site content images"
on storage.objects for delete
to authenticated
using (bucket_id = 'site-content' and public.is_bcb_admin());
