create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  setting_key text not null unique,
  setting_value text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists site_settings_key_idx on public.site_settings(setting_key);

alter table public.site_settings enable row level security;

drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert site settings" on public.site_settings;
create policy "admins can insert site settings"
on public.site_settings for insert
to authenticated
with check (public.is_bcb_admin() and updated_by = auth.uid());

drop policy if exists "admins can update site settings" on public.site_settings;
create policy "admins can update site settings"
on public.site_settings for update
to authenticated
using (public.is_bcb_admin())
with check (public.is_bcb_admin() and updated_by = auth.uid());

drop policy if exists "admins can delete site settings" on public.site_settings;
create policy "admins can delete site settings"
on public.site_settings for delete
to authenticated
using (public.is_bcb_admin());

create or replace function public.site_settings_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function public.site_settings_touch_updated_at();

-- Log changes in the existing BCB activity stream when available.
do $$
begin
  if to_regprocedure('public.log_bcb_activity()') is not null then
    execute 'drop trigger if exists site_settings_activity_log on public.site_settings';
    execute 'create trigger site_settings_activity_log after insert or update or delete on public.site_settings for each row execute function public.log_bcb_activity()';
  end if;
end $$;
