-- Production migration already applied via Supabase on 2026-08-31.
-- Tracked here to keep repository schema history aligned with production.

create table if not exists public.system_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  audience text not null default 'owner',
  severity text not null default 'info',
  category text not null default 'system',
  title text not null,
  body text,
  link text,
  dedupe_key text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.system_health_snapshots (
  id bigint generated by default as identity primary key,
  overall_status text not null default 'healthy',
  score integer not null default 100,
  checks jsonb not null default '{}'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.system_notifications enable row level security;
alter table public.system_health_snapshots enable row level security;

create index if not exists system_notifications_visible_idx on public.system_notifications (audience, user_id, is_read, created_at desc);
create unique index if not exists system_notifications_dedupe_idx on public.system_notifications (dedupe_key) where dedupe_key is not null;
create index if not exists system_health_snapshots_created_idx on public.system_health_snapshots (created_at desc);

-- Policies are intentionally idempotent in production and rely on the existing
-- is_bcb_staff(), is_bcb_admin() and is_bcb_owner() authorization helpers.
