create table if not exists public.quote_requests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  location text,
  project_type text,
  estimated_budget text,
  desired_start text,
  project_stage text,
  message text not null,
  status text not null default 'new' check (status in ('new','contacted','offer_sent','accepted','rejected','archived')),
  assigned_to uuid references auth.users(id) on delete set null,
  internal_notes text,
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quote_requests_status_idx on public.quote_requests(status, created_at desc);
create index if not exists quote_requests_created_at_idx on public.quote_requests(created_at desc);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_log_created_at_idx on public.activity_log(created_at desc);
create index if not exists activity_log_entity_idx on public.activity_log(entity_type, entity_id);

alter table public.quote_requests enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "public can submit quote requests" on public.quote_requests;
create policy "public can submit quote requests" on public.quote_requests for insert to anon, authenticated with check (source = 'website' and status = 'new');

drop policy if exists "staff can read quote requests" on public.quote_requests;
create policy "staff can read quote requests" on public.quote_requests for select to authenticated using (public.is_bcb_staff());

drop policy if exists "staff can update quote requests" on public.quote_requests;
create policy "staff can update quote requests" on public.quote_requests for update to authenticated using (public.is_bcb_staff()) with check (public.is_bcb_staff());

drop policy if exists "admins can delete quote requests" on public.quote_requests;
create policy "admins can delete quote requests" on public.quote_requests for delete to authenticated using (public.is_bcb_admin());

drop policy if exists "staff can read activity log" on public.activity_log;
create policy "staff can read activity log" on public.activity_log for select to authenticated using (public.is_bcb_staff());

create or replace function public.quote_requests_touch_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists quote_requests_set_updated_at on public.quote_requests;
create trigger quote_requests_set_updated_at before update on public.quote_requests for each row execute function public.quote_requests_touch_updated_at();

create or replace function public.log_bcb_activity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_actor uuid := auth.uid();
  v_entity_id text;
  v_summary text;
begin
  if tg_op = 'DELETE' then v_entity_id := old.id::text; else v_entity_id := new.id::text; end if;
  if tg_table_name = 'projects' then v_summary := coalesce(case when tg_op='DELETE' then old.title else new.title end, 'Proiect');
  elsif tg_table_name = 'project_media' then v_summary := coalesce(case when tg_op='DELETE' then old.title else new.title end, 'Fișier media');
  elsif tg_table_name = 'quote_requests' then v_summary := coalesce(case when tg_op='DELETE' then old.full_name else new.full_name end, 'Cerere ofertă');
  elsif tg_table_name = 'profiles' then v_summary := coalesce(case when tg_op='DELETE' then old.full_name else new.full_name end, 'Utilizator');
  else v_summary := tg_table_name;
  end if;
  insert into public.activity_log(actor_id, action, entity_type, entity_id, summary, metadata)
  values (v_actor, lower(tg_op), tg_table_name, v_entity_id, v_summary, jsonb_build_object('table', tg_table_name));
  if tg_op='DELETE' then return old; end if;
  return new;
end; $$;

revoke all on function public.log_bcb_activity() from public, anon, authenticated;

drop trigger if exists projects_activity_log on public.projects;
create trigger projects_activity_log after insert or update or delete on public.projects for each row execute function public.log_bcb_activity();
drop trigger if exists project_media_activity_log on public.project_media;
create trigger project_media_activity_log after insert or update or delete on public.project_media for each row execute function public.log_bcb_activity();
drop trigger if exists quote_requests_activity_log on public.quote_requests;
create trigger quote_requests_activity_log after insert or update or delete on public.quote_requests for each row execute function public.log_bcb_activity();
drop trigger if exists profiles_activity_log on public.profiles;
create trigger profiles_activity_log after update on public.profiles for each row execute function public.log_bcb_activity();