create table if not exists public.system_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  audience text not null default 'owner' check (audience in ('owner','admin','staff','user')),
  severity text not null default 'info' check (severity in ('info','success','warning','critical')),
  category text not null default 'system',
  title text not null,
  body text,
  link text,
  dedupe_key text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create unique index if not exists system_notifications_dedupe_idx on public.system_notifications(dedupe_key) where dedupe_key is not null;
create index if not exists system_notifications_user_read_created_idx on public.system_notifications(user_id,is_read,created_at desc);
create index if not exists system_notifications_audience_created_idx on public.system_notifications(audience,created_at desc);
alter table public.system_notifications enable row level security;
revoke all on public.system_notifications from anon;
grant select,update on public.system_notifications to authenticated;
create policy "staff read relevant notifications" on public.system_notifications for select to authenticated using (public.is_bcb_staff() and (user_id=(select auth.uid()) or (user_id is null and audience='staff') or (user_id is null and audience='admin' and public.is_bcb_admin()) or (user_id is null and audience='owner' and public.is_bcb_owner())));
create policy "users mark own visible notifications read" on public.system_notifications for update to authenticated using (public.is_bcb_staff() and (user_id=(select auth.uid()) or (user_id is null and audience='staff') or (user_id is null and audience='admin' and public.is_bcb_admin()) or (user_id is null and audience='owner' and public.is_bcb_owner()))) with check (public.is_bcb_staff() and (user_id=(select auth.uid()) or (user_id is null and audience='staff') or (user_id is null and audience='admin' and public.is_bcb_admin()) or (user_id is null and audience='owner' and public.is_bcb_owner())));

create table if not exists public.system_health_snapshots (
  id bigint generated by default as identity primary key,
  overall_status text not null default 'healthy' check (overall_status in ('healthy','attention','degraded')),
  score integer not null default 100 check (score between 0 and 100),
  checks jsonb not null default '{}'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists system_health_snapshots_created_idx on public.system_health_snapshots(created_at desc);
alter table public.system_health_snapshots enable row level security;
revoke all on public.system_health_snapshots from anon;
grant select on public.system_health_snapshots to authenticated;
create policy "owner reads system health" on public.system_health_snapshots for select to authenticated using (public.is_bcb_owner());

create index if not exists activity_log_actor_id_idx on public.activity_log(actor_id);
create index if not exists employee_certifications_created_by_idx on public.employee_certifications(created_by);
create index if not exists employee_compensation_updated_by_idx on public.employee_compensation(updated_by);
create index if not exists employee_documents_uploaded_by_idx on public.employee_documents(uploaded_by);
create index if not exists employee_equipment_created_by_idx on public.employee_equipment(created_by);
create index if not exists employee_equipment_updated_by_idx on public.employee_equipment(updated_by);
create index if not exists employee_leave_approved_by_idx on public.employee_leave(approved_by);
create index if not exists employee_leave_created_by_idx on public.employee_leave(created_by);
create index if not exists employees_created_by_idx on public.employees(created_by);
create index if not exists employees_manager_id_idx on public.employees(manager_id);
create index if not exists employees_updated_by_idx on public.employees(updated_by);
create index if not exists fleet_documents_vehicle_id_idx on public.fleet_documents(vehicle_id);
create index if not exists fleet_incident_files_uploaded_by_idx on public.fleet_incident_files(uploaded_by);
create index if not exists fleet_incidents_driver_id_idx on public.fleet_incidents(driver_id);
create index if not exists fleet_incidents_reviewed_by_idx on public.fleet_incidents(reviewed_by);
create index if not exists fleet_incidents_trip_id_idx on public.fleet_incidents(trip_id);
create index if not exists fleet_odometer_reconciliations_reconciled_by_idx on public.fleet_odometer_reconciliations(reconciled_by);
create index if not exists fleet_reports_driver_id_idx on public.fleet_reports(driver_id);
create index if not exists fleet_reports_generated_by_idx on public.fleet_reports(generated_by);
create index if not exists fleet_vehicle_drivers_user_id_idx on public.fleet_vehicle_drivers(user_id);
create index if not exists hr_alert_log_employee_id_idx on public.hr_alert_log(employee_id);
create index if not exists hr_alert_settings_updated_by_idx on public.hr_alert_settings(updated_by);
create index if not exists project_health_snapshots_generated_by_idx on public.project_health_snapshots(generated_by);
create index if not exists project_media_uploaded_by_idx on public.project_media(uploaded_by);
create index if not exists site_content_updated_by_idx on public.site_content(updated_by);
create index if not exists site_journal_entries_created_by_idx on public.site_journal_entries(created_by);
create index if not exists site_journal_entries_updated_by_idx on public.site_journal_entries(updated_by);
create index if not exists site_settings_updated_by_idx on public.site_settings(updated_by);
create index if not exists user_access_requests_reviewed_by_idx on public.user_access_requests(reviewed_by);